name: Rujia Wang
description: Personal website
menu:
 - page: About
   url: /about
 - page: Publications
   url: /papers
   links:
    - title: Working papers
      url: "#working-papers"
    - title: Published papers
      url: "#published-papers"
 - page: Research Projects
   url: /research
<!-- - page: Curriculum Vitae -->
<!--   url: /cv -->
 - page: Teaching
   url: /teaching
menu_external:
 - title: CS@Illinois Institute of Technology
   url: "https://science.iit.edu/computer-science"
 - title: Group page
   url: "TBA"
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: rujiawang.github.io
locale: en_GB
