name: Rujia Wang
description: Rujia Wang's Homepage
menu:
 - page: Home
   url: /
 - page: Publications
   url: /publications
 - page: Research
   url: /research
 - page: Teaching
   url: /teaching
 - page: Services
   url: /services
menu_external:
 - title: CS@Illinois Institute of Technology
   url: "https://science.iit.edu/computer-science"
mathjax: false
markdown: kramdown
encoding: utf-8
url: "https://rujiawang.github.io"
baseurl:
locale: en_GB
plugins:
  - jekyll-seo-tag
